### PR TITLE
Add an implementation of Value Tables

### PR DESCRIPTION
**Pull request by mohsen-ghaffari1992**

### CODE REVIEW

**Comment by wasowski** [comment]
What is this branch @mohsen-ghaffari1992 ?

**Comment by mohsen-ghaffari1992** [comment]
Is this in Symsim?
This includes my codes from two other papers.
If it is in Symsim, then should be deleted.

From: Andrzej Wąsowski ***@***.***>
Date: Wednesday, 28 September 2022 at 14.50
To: itu-square/symsim ***@***.***>
Cc: Mohsen Ghaffari ***@***.***>, Mention ***@***.***>
Subject: Re: [itu-square/symsim] Value table branch (PR #132)

What is this branch @mohsen-ghaffari1992<https://github.com/mohsen-ghaffari1992> ?

**Comment by mohsen-ghaffari1992** [comment]
OMG!!! NO!!!
The link which shared in email was to my profile and some other branches there.
Value table is the implementation of tables that we need for value iteration and policy iteration algorithms.


From: Andrzej Wąsowski ***@***.***>
Date: Wednesday, 28 September 2022 at 14.50
To: itu-square/symsim ***@***.***>
Cc: Mohsen Ghaffari ***@***.***>, Mention ***@***.***>
Subject: Re: [itu-square/symsim] Value table branch (PR #132)

What is this branch @mohsen-ghaffari1992<https://github.com/mohsen-ghaffari1992> ?

**Comment by wasowski** [comment]
OK - so this PR adds an implementations of VTable as opposed to QTable?

**Comment by mohsen-ghaffari1992** [comment]
Exactly

**Comment by wasowski** [comment]
OK. For the future, please try to describe what a PR contains briefly (in the opening comment, which is given when you create a PR).

**Comment by mohsen-ghaffari1992** [comment]
Sure!
Thanks for teaching these points to me!

**Comment by wasowski** [comment]
I have (possibly temporarily) removed the implementation of the `bestAction` method in `ConcreteVTable`. I am not entirely sure what that method should do, and whether the value table algorithms need it. How would this method pick the next action? 

A concrete simulator can only give us a reward for a sample (and consequently an infinite stream of random rewards for a given action), and the symbolic simulator can also give us more than one symbolic reward (because of branching and loop unrolling in symbolic simulators). Which reward we should return?

If `bestAction` is not needed by `VTable` algo then we should probably also remove it from the `ValueFunction` interface ... (it seems the design has still some rough edges).

**Pull request merged**
